/**
 * AXON Phrase Dictionary — 200+ NL phrases mapped to compressed stems.
 *
 * Entries are sorted longest-first at export time to ensure longest-match-first
 * semantics when applied sequentially.
 *
 * All keys are lowercase. Matching should be case-insensitive with word boundaries.
 */

const RAW_PHRASES: Record<string, string> = {
  // ── CI/CD & Version Control ──
  "pull request":               "PR",
  "pull requests":              "PRs",
  "code review":                "cr",
  "merge request":              "MR",
  "merge conflict":             "mconf",
  "branch":                     "br",
  "repository":                 "repo",
  "continuous integration":     "CI",
  "continuous deployment":      "CD",
  "pipeline":                   "pipe",
  "build failed":               "bld.fail",
  "build passed":               "bld.ok",
  "test suite":                 "tst.ste",
  "test suites":                "tst.stes",
  "unit tests":                 "utst",
  "integration tests":          "itst",
  "end to end tests":           "e2e",
  "code coverage":              "cov",
  "linting errors":             "lint.err",
  "deployment":                 "depl",
  "rollback":                   "rback",
  "hotfix":                     "hfix",
  "release candidate":          "RC",

  // ── Infrastructure & Services ──
  "database":                   "db",
  "health check":               "hchk",
  "health checks":              "hchks",
  "load balancer":              "lb",
  "kubernetes":                 "k8s",
  "docker container":           "ctr",
  "microservice":               "svc",
  "microservices":              "svcs",
  "api gateway":                "apigw",
  "message queue":              "mq",
  "rate limit":                 "rlim",
  "rate limiting":              "rlim",
  "authentication":             "auth",
  "authorization":              "authz",
  "api key":                    "apikey",
  "environment variable":       "envvar",
  "environment variables":      "envvars",
  "configuration":              "cfg",
  "infrastructure":             "infra",
  "monitoring":                 "mon",
  "observability":              "obs",
  "telemetry":                  "telem",
  "memory usage":               "mem.use",
  "cpu usage":                  "cpu.use",
  "disk usage":                 "disk.use",
  "exponential backoff":        "expbkf",
  "circuit breaker":            "cbrk",
  "timeout":                    "T/O",
  "connection pool":            "cpool",

  // ── LLM / Agent Domain ──
  "large language model":       "LLM",
  "language model":             "LLM",
  "orchestrator agent":         "orch",
  "orchestrator":               "orch",
  "worker agent":               "w.agt",
  "worker agents":              "w.agts",
  "tool call":                  "tcall",
  "tool calls":                 "tcalls",
  "function call":              "fcall",
  "system prompt":              "syspmt",
  "context window":             "ctx.win",
  "token limit":                "tok.lim",
  "embedding":                  "emb",
  "embeddings":                 "embs",
  "vector store":               "vstore",
  "retrieval augmented":        "RAG",
  "chain of thought":           "CoT",
  "structured output":          "s.out",
  "structured data":            "s.data",
  "multi-agent":                "m.agt",
  "multi agent":                "m.agt",
  "agent communication":        "agt.com",
  "knowledge base":             "kb",
  "semantic search":            "sem.srch",

  // ── Operations & Status ──
  "error occurred":             "ERR",
  "exception thrown":           "exc",
  "stack trace":                "strace",
  "null pointer":               "NPE",
  "status code":                "sc",
  "response time":              "rtime",
  "latency":                    "lat",
  "throughput":                 "tput",
  "request body":               "req.body",
  "response body":              "res.body",
  "successfully completed":     "ok",
  "successfully":               "ok",
  "in progress":                "WIP",
  "pending":                    "pend",
  "failed":                     "fail",
  "passing":                    "pass",
  "report back":                "rpt",
  "send a report":              "rpt",
  "send report":                "rpt",
  "generate report":            "gen.rpt",
  "summary report":             "sum.rpt",
  "status update":              "stat.upd",
  "status report":              "stat.rpt",
  "all services":               "svcs.ALL",
  "all tests":                  "tst.ALL",
  "security vulnerabilities":   "sec.vuln",
  "security vulnerability":     "sec.vuln",
  "coding standards":           "std",
  "structured assessment":      "assess.s",

  // ── Common verbs & operations ──
  "validate":                   "valid",
  "validation":                 "valid",
  "validating":                 "valid",
  "aggregate":                  "agg",
  "aggregated":                 "agg",
  "aggregating":                "agg",
  "summarize":                  "sum",
  "summarizing":                "sum",
  "summary":                    "sum",
  "investigate":                "inv",
  "investigating":              "inv",
  "investigation":              "inv",
  "resolution":                 "fix",
  "resolving":                  "fix",
  "resolved":                   "fix",
  "processing":                 "proc",
  "process":                    "proc",
  "processed":                  "proc",
  "generating":                 "gen",
  "generate":                   "gen",
  "generated":                  "gen",
  "extracting":                 "ext",
  "extract":                    "ext",
  "extracted":                  "ext",
  "analyzing":                  "anl",
  "analyze":                    "anl",
  "analysis":                   "anl",
  "transform":                  "xfm",
  "transforming":               "xfm",
  "transformed":                "xfm",
  "filtering":                  "filt",
  "filter":                     "filt",
  "filtered":                   "filt",
  "scheduling":                 "sched",
  "schedule":                   "sched",
  "scheduled":                  "sched",
  "verifying":                  "ver",
  "verify":                     "ver",
  "verified":                   "ver",
  "verification":               "ver",
  "deploying":                  "depl",
  "deploy":                     "depl",
  "deployed":                   "depl",
  "retry":                      "retry",
  "retrying":                   "retry",
  "restarting":                 "rst",
  "restart":                    "rst",
  "restarted":                  "rst",
  "executing":                  "exec",
  "execute":                    "exec",
  "execution":                  "exec",

  // ── Common nouns ──
  "service":                    "svc",
  "services":                   "svcs",
  "application":                "app",
  "applications":               "apps",
  "environment":                "env",
  "performance":                "perf",
  "notification":               "notif",
  "notifications":              "notifs",
  "transaction":                "txn",
  "transactions":               "txns",
  "connection":                 "conn",
  "connections":                "conns",
  "credentials":                "creds",
  "customer":                   "cust",
  "customers":                  "custs",
  "upstream":                   "up",
  "downstream":                 "down",
  "response":                   "rsp",
  "request":                    "req",
  "requests":                   "reqs",
  "records":                    "recs",
  "record":                     "rec",
  "information":                "info",
  "production":                 "prod",
  "development":                "dev",
  "operation":                  "op",
  "operations":                 "ops",
  "document":                   "doc",
  "documents":                  "docs",
  "migration":                  "migr",
  "replication":                "repl",
  "cluster":                    "clu",
  "provider":                   "pvdr",
  "security":                   "sec",
  "payment":                    "pay",
  "account":                    "acct",
  "number":                     "#",
  "maximum":                    "max",
  "minimum":                    "min",
  "seconds":                    "s",
  "minutes":                    "min",
  "workers":                    "wkrs",
  "worker":                     "wkr",
  "findings":                   "res",
  "results":                    "res",
  "result":                     "res",
  "immediately":                "imm",
  "immediately escalate":       "imm.esc",
  "root cause":                 "root",
  "resource constraints":       "res.lim",
  "exceeding limits":           "over.lim",
  "response team":              "rsp.team",
  "incident response":          "inc.rsp",
  "data warehouse":             "dwh",
  "data integrity":             "dat.int",
  "data source":                "dsrc",
  "data sources":               "dsrcs",
  "fraud detection":            "fraud",
  "error details":              "err.det",
  "critical alert":             "CRIT",
  "returning":                  "ret",
  "returning timeout":          "ret.T/O",
  "approximate":                "aprx",
  "approximately":              "~",
  "threshold":                  "thr",
  "thresholds":                 "thrs",
  "recommendations":            "recs",
  "compliance":                 "compl",
  "workflow":                   "wflow",
  "coordinate":                 "coord",
  "coordinating":               "coord",
  "instruct":                   "inst",
  "comprehensive":              "full",
  "requested":                  "req'd",
  "requesting":                 "req'g",
  "percentage":                 "pct",
  "percent":                    "pct",
  "address":                    "addr",
  "issues":                     "iss",
  "retrieved":                  "ret'd",
  "retrieve":                   "get",
  "constraints":                "lim",
  "containers":                 "ctrs",
  "container":                  "ctr",
  "dashboards":                 "dash",
  "dashboard":                  "dash",
  "escalate":                   "esc",
  "flagged":                    "flag",
  "severity":                   "sev",
};

/**
 * Sorted phrase entries — longest key first for greedy matching.
 * Each entry: [regex, replacement]
 */
export const PHRASE_MAP: Array<[RegExp, string]> = Object.entries(RAW_PHRASES)
  .sort((a, b) => b[0].length - a[0].length)
  .map(([phrase, stem]) => {
    const escaped = phrase.replace(/[.*+?^${}()|[\]\\-]/g, "\\$&");
    return [new RegExp(`\\b${escaped}\\b`, "gi"), stem];
  });

/** Raw phrase dictionary for inspection/testing */
export const RAW_PHRASE_DICT = RAW_PHRASES;
